CREATE TABLE cidade(
	id BIGINT  AUTO_INCREMENT NOT NULL,
	nome_cidade VARCHAR(80) NOT NULL,
	nome_estado VARCHAR(80) NOT NULL,
	CONSTRAINT pk_cidade PRIMARY KEY (id)

) ENGINE=InnoDB default charset=utf8;

ALTER TABLE cozinha
MODIFY COLUMN nome VARCHAR(80) NOT NULL;